"""Loads the .docx knowledge base into section/page-tagged text blocks.

The document is generated by data/generate_kb_doc.py with one explicit page break
per section (title page = page 1, section N = page N+1), so page numbers can be
recovered exactly by counting page-break runs while walking the paragraphs —
no PDF rendering or heuristics required.
"""

from dataclasses import dataclass

from docx import Document
from docx.oxml.ns import qn


@dataclass
class SectionBlock:
    section: str
    page: int
    text: str


def _has_page_break(paragraph) -> bool:
    for run in paragraph.runs:
        for br in run._element.findall(qn("w:br")):
            if br.get(qn("w:type")) == "page":
                return True
    return False


def load_docx_sections(path) -> list[SectionBlock]:
    doc = Document(str(path))

    sections: list[SectionBlock] = []
    current_heading = None
    current_heading_page = None
    current_lines: list[str] = []
    page = 1

    def flush():
        if current_heading is not None:
            sections.append(SectionBlock(
                section=current_heading,
                page=current_heading_page,
                text="\n".join(current_lines).strip(),
            ))

    for para in doc.paragraphs:
        if _has_page_break(para):
            page += 1
            continue

        style = para.style.name if para.style else ""
        text = para.text.strip()
        if not text:
            continue

        if style.startswith("Heading"):
            flush()
            current_heading = text
            current_heading_page = page
            current_lines = []
        elif style == "Title" or current_heading is None:
            continue  # title / subtitle / provenance note before section 1
        else:
            # Bullet paragraph text already carries its own literal "- " prefix
            # (see data/generate_kb_doc.py); List Bullet style only adds a glyph
            # in Word's rendering, not to para.text, so no prefix is added here.
            current_lines.append(text)

    flush()
    return sections


if __name__ == "__main__":
    import sys
    from config import KB_DOCX_PATH

    path = sys.argv[1] if len(sys.argv) > 1 else KB_DOCX_PATH
    blocks = load_docx_sections(path)
    for b in blocks:
        print(f"[page {b.page}] {b.section} ({len(b.text)} chars)")
